
#+TITLE: Captured
#+OPTIONS: title:nil H:2 html-postample:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=EB+Garamond" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="capture.css" />
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1">
* Inbox
** React Hooks in PureScript
 Source: [2019-03-21 Thu], [[https://github.com/spicydonuts/purescript-react-basic-hooks][spicydonuts/purescript-react-basic-hooks: An implementation of React hooks on top of purescript-react-basic]]
  #+BEGIN_QUOTE
 This library provides the React.Basic.Hooks module, which can completely replace the React.Basic module. It borrows a few types from the current React.Basic module like ReactComponent and JSX to make it easy to use both versions in the same project.
 #+END_QUOTE
** Nice quote about programming
 Source: [2019-03-21 Thu], [[http://eloquentjavascript.net/1st_edition/chapter6.html#p61d9c58b7ccd55b][Functional Programming -- Eloquent JavaScript]]
  #+BEGIN_QUOTE
 Admittedly, in most cases, breaking a program does not cause any large explosions. But when a program, by someone's ignorant tinkering, has degenerated into a ramshackle mass of errors, reshaping it into something sensible is a terrible labour ― sometimes you might just as well start over.
 #+END_QUOTE
**  [[https://www.nytimes.com/2019/03/12/technology/how-to-disappear-surveillance-state.html][How a Bitcoin Evangelist Made Himself Vanish, in 15 (Not So Easy) Steps - The New York Times]]  :ARCHIVE:
 Captured On: [2019-03-21 Thu 11:04]

 Impressive 

**  [[https://blogarithms.github.io/articles/2019-03/cracking-dp-part-one][The One On Dynamic Programming! | Blogarithms]] 
 Captured On: [2019-03-21 Thu 11:04]

** [PDF] [[https://web.archive.org/web/20190315213523/https:/stefan-klinger.de/files/monadGuide.pdf][A hacker's guide to Monad]] 
 Captured On: [2019-03-21 Thu 11:09]

** [PDF] [[https://web.archive.org/web/20190308183038/https:/wiki.haskell.org/wikiupload/e/e9/Typeclassopedia.pdf][TypeClassopedia]] 
 Captured On: [2019-03-21 Thu 11:11]

** [PDF] [[https://web.archive.org/web/20190308182743/http:/www.staff.city.ac.uk/~ross/papers/Applicative.pdf][Applicative Programming with effects]] 
 Captured On: [2019-03-21 Thu 11:12]

** [PDF] [[https://web.archive.org/web/20190308075944/http:/homepages.inf.ed.ac.uk/wadler/papers/marktoberdorf/baastad.pdf][Monad for functional programming]] 
 Captured On: [2019-03-21 Thu 11:15]
 
** Life in game development
 Source: [2019-03-21 Thu], [[https://www.polygon.com/2019/3/5/18233699/game-developer-layoffs-unions-katie-chironis][What it’s like to be laid off from your video game studio - Polygon]]
  #+BEGIN_QUOTE
 Dream jobs are a funny thing. You can make money doing what you love. That’s pretty cool. But after multiple interstate, or intercontinental, moves for the sake of finding a new job, or rebooting your social life for the fifth time, or having to explain to your daughter why she’s changing schools and leaving her friends, the cool parts lose their luster.

 And once that luster is gone, a dream job is just another job.
 #+END_QUOTE

** [PDF] [[http://web.archive.org/web/20130823222012/http:/www.cs.tufts.edu/~nr/comp150fp/archive/richard-bird/sudoku.pdf][A program to solve Sudoku]] 
 Captured On: [2019-03-21 Thu 11:19]
** Series of introduction to Functional Programming
 Source: [2019-03-22 Fri], [[https://codurance.com/2018/08/09/the-functional-style-part-1/][The Functional Style - Part 1 | Codurance | Craft at Heart | London | Barcelona]]
  #+BEGIN_QUOTE
 So over the course of this nine part series I want to cover the topics that I think are important in functional programming. I will try to explain first-class and higher-order functions, map and reduce, currying, function composition and monads, lazy evaluation and persistent data structures. All will be illustrated with code examples wherever possible. Most (but not all) of the code will be in Java, Groovy and Clojure because that is what I know best.

 Topics you will not find in this series include monoids, functors, applicatives, and category theory. 
 #+END_QUOTE
** Figma rewrite parts of its TypeScript multiplayer server with Rust :ARCHIVE:
 Source: [2019-03-22 Fri], [[https://www.figma.com/blog/rust-in-production-at-figma/][How Mozilla’s Rust dramatically improved our server-side performance]]
 
Their problem:
  #+BEGIN_QUOTE
 The main problem with the old server was the unpredictable latency spikes during syncing. The server was written in TypeScript and, being single-threaded, couldn’t process operations in parallel. That meant a single slow operation would lock up the entire worker until it was complete. A common operation is to encode the document and Figma documents can get very large, so operations would take an arbitrarily-long amount of time. Users connected to that worker would be unable to sync their changes in the meantime.
 #+END_QUOTE

And the solution:
#+BEGIN_QUOTE
we did by moving the performance-sensitive parts of the multiplayer server into a separate child process. That child process is written in Rust and communicates with its host process using stdin and stdout.
#+END_QUOTE
** Recover the dropped git stash :ARCHIVE:
 Source: [2019-03-22 Fri], [[http://inlehmansterms.net/2015/09/19/recover-a-dropped-git-stash/][Recover a dropped Git stash - In Lehman's Terms]]
  #+BEGIN_QUOTE
 Dangling commit: commits that not linked to any commit / branch,.. for most of the times, dropped stashes can be found as a dangling commit.

 We pipe the output of git fsck thru awk to only log the hashes of the dangling commits.

 git fsck --no-reflogs | awk '/dangling commit/ {print $3}'

 This still might produce a number of hashes. To better determine which hash corresponds to the commit you dropped from the stash, you can pass the hashes to git log or git show to get more information.
 
 When you found the hash, checkout to revert it back.
 #+END_QUOTE


** Article: Beating the Averages

Captured On: [2019-03-22 12:24:26]

Beating the Averages by Paul Graham
http://www.paulgraham.com/avg.html?viewfullsite=1

** Re-educating Rita

Captured On: [2019-03-22 21:28:44] from email

"Character skills" such as perseverance, sociability and curiosity, will be increasingly important in a world of greater automation
https://outline.com/PpFxaL


** Article: How to get customers for your side project

Captured On: [2019-03-24 01:10:25] from email

How I got my first 10 customers for my side-project and what Ive learned from them
https://blog.cronhub.io/how-i-acquired-my-first-10-customers-for-cronhub/
https://medium.freecodecamp.org/how-i-acquired-my-first-10-customers-for-my-side-project-c4ee892a70a2


** A complete guide to threads in Node.js – LogRocket

Captured On: [2019-03-24 14:49:39] from email

A complete guide to threads in Node.js  LogRocket
https://blog.logrocket.com/a-complete-guide-to-threads-in-node-js-4fa3898fe74f


** Opinion | Forget Self-Driving Cars. Bring Back the Stick Shift. - The
 New York Times

Captured On: [2019-03-24 14:52:14] from email

Opinion | Forget Self-Driving Cars. Bring Back the Stick Shift. - The New York Times
https://www.nytimes.com/2019/03/23/opinion/sunday/stick-shift-cars.html


** Article: How to turn a Raspberry Pi into a game console

Captured On: [2019-03-24 23:22:04] from email

How to turn a Raspberry Pi into a game console - 
https://www.engadget.com/2019/03/24/how-to-turn-a-raspberry-pi-into-a-game-console/
The Recalbox manager can do other things, too. You can access a variety 
of settings from the Web manager, including wireless network settings 
and shaders. You can even press a button to take a screenshot when 
you're playing games. If you don't like the browser-based manager, 
you can also access
 your Raspberry Pi in Windows Explorer or Finder on Mac, similar to how you'd use a 
network-attached storage device
.


** Article: The Inside Story of Reddit's Redesign

Captured On: [2019-03-24 23:25:43] from email

https://www.wired.com/story/reddit-redesign/
But another goal goes much deeper: changing the constitution of the 
site, making it more welcoming to people who never thought they could 
find a home there before. On the new Reddit, we are all just aliens, 
exploring the vast community of foreign planets, trying to find our 
place in the universe.


** Utilities for efficient filesystem navigation in emacs

Captured On: [2019-03-25 09:39:40] from email

https://lorefnon.me/2015/11/15/utilities-for-efficient-filesystem-navigation-in-emacs.html
While Emacs is a fairly productive editor on its own, for navigating 
through the files in a large project a few community contributed 
extensions can make things a lot easier


** Link to open Gmail in compose mode :ARCHIVE:

Captured On: [2019-03-25 09:49:38] from email

https://mail.google.com/mail/?fs=1&view=cm&shva=1&su=
Note: If you want to program with this just start adding values to the end of the url above. I have already added a blank subject by ending the above url with &su=, so to add a subject just add a string to the end of the url above. For body, to, cc, and bcc fields use &body=, &to=, &cc=, &bcc= all with strings after word. Depending on your browser you may need to URI escape your field values.


** Avoid Debt :ARCHIVE:

Captured On: [2019-03-25 10:12:12] from email

http://www.fourmilab.ch/etexts/www/barnum/moneygetting/moneygetting_chap4.html
Debt robs a man of his self-respect, and makes him almost despise himself. Grunting and groaning and working for what he has eaten up or worn out, and now when he is called upon to pay up, he has nothing to show for his money; this is properly termed working for a dead horse.


** DO NOT SCATTER YOUR POWERS :ARCHIVE:

Captured On: [2019-03-25 11:42:00] from email

http://www.fourmilab.ch/etexts/www/barnum/moneygetting/moneygetting_chap12.html
Engage in one kind of business only, and stick to it faithfully until you succeed, or until your experience shows that you should abandon it. A constant hammering on one nail will generally drive it home at last, so that it can be clinched. When a man's undivided attention is centered on one object, his mind will constantly be suggesting improvements of value, which would escape him if his brain was occupied by a dozen different subjects at once. Many a fortune has slipped through a man's fingers because he was engaged in too many occupations at a time. There is good sense in the old caution against having too many irons in the fire at once. 


** Waiting for an element to be created :ARCHIVE:

Captured On: [2019-03-25 16:13:50] from email

https://paul.kinlan.me/waiting-for-an-element-to-be-created/
a small function called waitForElement that uses the MutationObserver to look for when an element with a given id is added to the DOM. When that element has been detected it will resolve the promise and return the element.


** How, in general, does Node.js handle 10,000 concurrent requests? -
 Stack Overflow

Captured On: [2019-03-26 00:51:43] from email

https://stackoverflow.com/questions/34855352/how-in-general-does-node-js-handle-10-000-concurrent-requests


** Functional Thinking

Captured On: [2019-03-26 01:04:59] from email

https://www.ebayinc.com/stories/blogs/tech/functional-thinking/
Imperative thinking became so natural, we see past verbose code. Nonetheless, it requires reading and understanding four lines of code to get to what the code is doing.
The real gain is not having three lines of code less. Very similar problems occur over and over again, sometimes on the same method. If the functional approach is used, every time we'll write less logic, reducing the odds of introducing errors.


** nealford.com • Functional Thinking

Captured On: [2019-03-26 01:05:38] from email

http://nealford.com/functionalthinking.html










** Use Pandoc in Python :ARCHIVE:

Captured On: [2019-03-26 10:06:51]

#+BEGIN_EXPORT html
<div dir="ltr"><div><a href="https://pypi.org/project/pyandoc/">https://pypi.org/project/pyandoc/</a></div><div><br></div><div>First, install Pyandoc:</div><div style="margin-left:40px"><pre>pip install pyandoc</pre></div><div>Then use it like this:</div><div style="margin-left:40px"><pre>doc <span class="gmail-pl-k">=</span> pandoc.Document()
doc.markdown <span class="gmail-pl-k">=</span> <span class="gmail-pl-s"><span class="gmail-pl-pds">&#39;&#39;&#39;</span></span>
<span class="gmail-pl-s"># I am an H1 Tag</span>
<span class="gmail-pl-s"></span>
<span class="gmail-pl-s">* bullet point</span>
<span class="gmail-pl-s">* more points</span>
<span class="gmail-pl-s">* point with [link](<a href="http://kennethreitz.com">http://kennethreitz.com</a>)!</span>
<span class="gmail-pl-s"><span class="gmail-pl-pds">&#39;&#39;&#39;<br>print doc.rst</span></span></pre></div><br></div>
#+END_EXPORT

** How the Brain Links Gestures, Perception and Meaning | Quanta Magazine

Captured On: [2019-03-26 10:09:04]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://www.quantamagazine.org/how-the-brain-links-gestures-perception-and-meaning-20190325/">https://www.quantamagazine.org/how-the-brain-links-gestures-perception-and-meaning-20190325/</a><br><br>Gesture allows us to express ourselves, and it also shapes the way we understand and interpret others</div>
#+END_EXPORT

** How to price your side-project - Tigran Hakobyan's personal blog

Captured On: [2019-03-26 16:20:40]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://tik.dev/how-to-price-your-side-project/">https://tik.dev/how-to-price-your-side-project/</a><br><br>There are three pricing strategies for SaaS products.<br><div><br></div><div style="margin-left:40px"><b>Cost-Plus Pricing</b></div><div style="margin-left:40px"><br>First, you calculate everything that costs money for your project and then add a healthy margin on top of it. The margin is your profit, and it represents the value that you give to your customers.<br><br>The challenge with this pricing strategy is the unpredictability of the future. If your costs unexpectedly go up in the future your profit margin will drop and you will have to increase your prices.<br></div><div style="margin-left:40px"><br></div><div style="margin-left:40px"><b>Competitor-Based Pricing</b></div><div style="margin-left:40px"><br>Check their pricing tables so you can come up with yours.<br><br>This pricing strategy is simple and less prone to be wrong. Your future customers wont think that your product is too expensive or too cheap.<br><br>The one downside is that you dont want to be guided by your competitors from day one. This strategy mostly used in combination with other pricing models.<br></div><div style="margin-left:40px"><br></div><div style="margin-left:40px"><b>Value-based pricing</b></div><div style="margin-left:40px"><br>Solely based on your customer surveys and research. You want to know how much your customers are willing to pay for your product, and the only way to do so is to go and talk to them. Most companies use in-product surveys to collect this data.<br><br>However, this model can only be applied after some initial iterations when you have a decent customer base.<br></div><br>You may want to re-apply this strategy often, because your customer base and the market needs keep changing.</div>
#+END_EXPORT

** String.prototype.match() - JavaScript | MDN :ARCHIVE:

Captured On: [2019-03-26 21:32:58]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match">https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match</a><br><br><div>- If the g flag is used, all results matching the complete regular expression will be returned, but capturing groups will not.</div><div>- if the g flag is not used, only the first complete match and its related capturing groups are returned. In this case, the returned item will have additional properties as described below.</div><div>- if you want to obtain capture groups and the global flag is set,you need to use <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec" title="The exec() method executes a search for a match in a specified string. Returns a result array, or null."><code>RegExp.exec()</code></a> instead.</div></div>
#+END_EXPORT

** Regrets of the Dying - Bronnie Ware

Captured On: [2019-03-27 14:21:45]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://bronnieware.com/blog/regrets-of-the-dying/">https://bronnieware.com/blog/regrets-of-the-dying/</a><br><br><b>1. I wish Id had the courage to live a life true to myself, not the life others expected of me.<br></b><br>This was the most common regret of all. When people realise that their life is almost over and look back clearly on it, it is easy to see how many dreams have gone unfulfilled. Most people had not honoured even a half of their dreams and had to die knowing that it was due to choices they had made, or not made.<br><br>It is very important to try and honour at least some of your dreams along the way. From the moment that you lose your health, it is too late. Health brings a freedom very few realise, until they no longer have it.<br><b><br>2. I wish I hadnt worked so hard.</b><br><br>This came from every male patient that I nursed. They missed their childrens youth and their partners companionship. Women also spoke of this regret. But as most were from an older generation, many of the female patients had not been breadwinners. All of the men I nursed deeply regretted spending so much of their lives on the treadmill of a work existence.<br><br>By simplifying your lifestyle and making conscious choices along the way, it is possible to not need the income that you think you do. And by creating more space in your life, you become happier and more open to new opportunities, ones more suited to your new lifestyle.<br><br><b>3. I wish Id had the courage to express my feelings.</b><br><br>Many people suppressed their feelings in order to keep peace with others. As a result, they settled for a mediocre existence and never became who they were truly capable of becoming. Many developed illnesses relating to the bitterness and resentment they carried as a result.<br><br>We cannot control the reactions of others. However, although people may initially react when you change the way you are by speaking honestly, in the end it raises the relationship to a whole new and healthier level. Either that or it releases the unhealthy relationship from your life. Either way, you win.<br><br><b>4. I wish I had stayed in touch with my friends.</b><br><br>Often they would not truly realise the full benefits of old friends until their dying weeks and it was not always possible to track them down. Many had become so caught up in their own lives that they had let golden friendships slip by over the years. There were many deep regrets about not giving friendships the time and effort that they deserved. Everyone misses their friends when they are dying.<br><br>It is common for anyone in a busy lifestyle to let friendships slip. But when you are faced with your approaching death, the physical details of life fall away. People do want to get their financial affairs in order if possible. But it is not money or status that holds the true importance for them. They want to get things in order more for the benefit of those they love. Usually though, they are too ill and weary to ever manage this task. It all comes down to love and relationships in the end. That is all that remains in the final weeks, love and relationships.<br><br><b>5. I wish that I had let myself be happier.</b><br><br>This is a surprisingly common one. Many did not realise until the end that happiness is a choice. They had stayed stuck in old patterns and habits. The so-called comfort of familiarity overflowed into their emotions, as well as their physical lives. Fear of change had them pretending to others, and to their selves, that they were content. When deep within, they longed to laugh properly and have silliness in their life again.<br><br>When you are on your deathbed, what others think of you is a long way from your mind. How wonderful to be able to let go and smile again, long before you are dying.<br><br><b>Life is a choice. It is YOUR life. </b></div>
#+END_EXPORT

** Future-proof Reading – αλεx π :ARCHIVE:

Captured On: [2019-03-28 10:18:42]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://medium.com/@ifesdjeen/future-proof-reading-25303e2b57d3">https://medium.com/@ifesdjeen/future-proof-reading-25303e2b57d3</a><br><br><b><font size="2">Drawbacks of sparse highlights/notes</font></b><br><br>We end up concentrating on the details instead of the general ideas. details tend to wear down and get forgotten.<br>If you happened to find an idea that you believe belongs to the core of the book somewhere in the middle, it might be hard to navigate back to it, even with good set of markers.<br><br>Writing notes on the fields is also hard because the fields are narrow. After finishing a book, its hard to go through them in order to refine a conclusion and formulate a final statement on the book.<br><br>When going back to a highlighted paragraph, its difficult to understand why exactly this paragraph was important... because the context is hard to capture, using it quickly isnt possible, so you might have to re-read several pages to understand why the highlight was there on the first place.<br><div><br></div><div><b>Benefits of dense notes and summaries</b></div><br>Dense notes (ones which are not directly attached to the book) can serve several purposes. You can keep two sets of notes:<br><ol><li>temporary working notes: will get processed afterwards and mostly kept to make sure you do not miss the important things</li><li>chapter-by-chapter notes: theyre useful both for an immediate recollection (when you just finished the chapter, its still easy for you to recall the details and give an executive summary of the ideas, if the book is nonfiction or happenings if youre reading a fiction book) and for searching for a meaning (in nonfiction) and/or a plot (mostly in fiction books or stories).</li></ol>When youre done with a book, you can go through the two sets of notes, throw away the duplicates, refine wording and ensure the consistency, discard the temporary ones and leave the chapter-by-chapter summaries for the cases when you have to go back to the details of the book.<br><br>Writing a summary after each chapter helps you to capture the ideas before they got wiped out from the memory. Retention is further improved while editing notes and working on the summary.<br><br>After that, you can put together an executive summary, something like a short review for your future self that explains the most important concepts, ideas and, possibly, the meaning of the book. In the end, this is what were looking for.<br><br><b>Making a System</b><br><br>Ive started reading at least a chapter at a time, since it was improving understanding, started getting a feel for the book structure better.<br><br>Having the notes systematised and indexed in electronic format will definitely be helpful if I ever need to go back to these books. If it happens that the notes will be never needed again, I still do not think that the time spent writing them was wasted: I use them as an analytical instrument, not only like an external memory.</div>
#+END_EXPORT

** Repetition as an Advertisement Technique | Chron.com

Captured On: [2019-03-29 00:28:18]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://smallbusiness.chron.com/repetition-advertisement-technique-24437.html">https://smallbusiness.chron.com/repetition-advertisement-technique-24437.html</a><br><br>One of the leading theories on the effect of repetition on consumer behavior was developed in the 1970s by University of Toronto psychology professor Daniel Berlyne. This theory, called two-factor theory, or wear-in/wear-out, suggests that repetition has a positive effect for a period, and then begins to have a negative effect.<br><br><div>During the first phase, called wear-in, repetition of an ad allows consumers to become familiar with the brand. In this phase, repetition can overcome consumer reluctance to purchase a new product or brand. As the repetition continues, consumers become used to the brand and may enter a second phase, called wear-out. In the wear-out phase, consumers become tired of hearing about the brand and continued repetition of ads can cause consumers to stop buying the product or brand.</div><div><br></div><div>Consumers tend to pay more attention to an ad that is for a completely 
new product or brand, than to an ad for a product or brand with which 
they are already familiar. The new ad will be more interesting to 
consumers, so they will be more likely to take note of it.</div><div><br></div><div>Repetition of an ad may signal to consumers that the brand or product is a good buy, or a quality product. May convince consumers that the manufacturer is willing to spend a lot 
of money on advertising because the product is a good one.</div></div>
#+END_EXPORT

** Everything I know about freelancing | Andy Adams

Captured On: [2019-03-29 13:40:57]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://andyadams.org/everything-i-know-about-freelancing/">https://andyadams.org/everything-i-know-about-freelancing/</a><br><br></div>
#+END_EXPORT

** Productivity Isn’t About Time Management. It’s About Attention Management. - The New York Times
   
   

Captured On: [2019-03-31 23:05:57]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://www.nytimes.com/2019/03/28/smarter-living/productivity-isnt-about-time-management-its-about-attention-management.html">https://www.nytimes.com/2019/03/28/smarter-living/productivity-isnt-about-time-management-its-about-attention-management.html</a><br><br></div>
#+END_EXPORT

** A Guide to Combining Fonts | Better Web Type

Captured On: [2019-04-02 23:59:54]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://betterwebtype.com/combining-fonts-guide">https://betterwebtype.com/combining-fonts-guide</a><br><br></div>
#+END_EXPORT

** From Show HN to Series D · Segment Blog

Captured On: [2019-04-03 00:24:21]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://segment.com/blog/show-hn-to-series-d/">https://segment.com/blog/show-hn-to-series-d/</a><br><br></div>
#+END_EXPORT

** 25 Years Later: Interview with Linus Torvalds | Linux Journal

Captured On: [2019-04-03 00:24:42]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://www.linuxjournal.com/content/25-years-later-interview-linus-torvalds">https://www.linuxjournal.com/content/25-years-later-interview-linus-torvalds</a><br><br></div>
#+END_EXPORT

** How eBay Uses Microinteractions to Delight Customers

Captured On: [2019-04-04 17:13:10]

#+BEGIN_EXPORT html
<div dir="ltr"><div><a href="https://www.ebayinc.com/stories/blogs/tech/how-ebay-uses-microinteractions-to-delight-customers-in-china/">https://www.ebayinc.com/stories/blogs/tech/how-ebay-uses-microinteractions-to-delight-customers-in-china/</a></div><div><br></div><div>microinteractions can positively impact our experience at an even larger scale. They can affect the <strong>perception of the brand</strong> or the <strong>speed of the application</strong>. They can impact the <strong>trust a user has</strong> in the product or <strong>help educate users</strong> on complex features. They can even simply be used to<strong> delight the users</strong> at important moments.</div><br></div>
#+END_EXPORT

** A Complete Beginner's Guide to Vue - DEV Community 👩‍💻👨‍💻

Captured On: [2019-04-04 23:00:37]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://dev.to/aspittel/a-complete-beginners-guide-to-vue-422n">https://dev.to/aspittel/a-complete-beginners-guide-to-vue-422n</a><br><br></div>
#+END_EXPORT

** Second-Order Thinking: What Smart People Use to Outperform

Captured On: [2019-04-05 00:42:57]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://fs.blog/2016/04/second-order-thinking/">https://fs.blog/2016/04/second-order-thinking/</a><br><div><br></div><div>Second order thinkers ask themselves the question <a href="https://fs.blog/2015/12/garrett-hardin-three-filters/">And then what?</a>
 This means thinking about the consequences of repeatedly eating a 
chocolate bar when you are hungry and using that to inform your 
decision. If you do this youre more likely to eat something healthy.</div></div>
#+END_EXPORT

** Recognising palindromes in Haskell

Captured On: [2019-04-05 16:10:57]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="http://www.haskellcraft.com/craft3e/Palindromes.html">http://www.haskellcraft.com/craft3e/Palindromes.html</a><br><br></div>
#+END_EXPORT

** Thinking in Ramda

Captured On: [2019-04-08 00:34:13]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="http://randycoulman.com/blog/categories/thinking-in-ramda/">http://randycoulman.com/blog/categories/thinking-in-ramda/</a><br><br></div>
#+END_EXPORT

** The Science Behind Why You Procrastinate In The Afternoon

Captured On: [2019-04-10 11:12:10]

#+BEGIN_EXPORT html

#+END_EXPORT

** Download playlist with youtube-dl

Captured On: [2019-04-10 14:07:51]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://askubuntu.com/questions/564567/how-to-download-playlist-from-youtube-dl">https://askubuntu.com/questions/564567/how-to-download-playlist-from-youtube-dl</a><br><br><span style="background-color:rgb(238,238,238)"><span style="font-family:monospace,monospace">youtube-dl --extract-audio --audio-format mp3 -o &quot;%(title)s.%(ext)s&quot; &lt;url to playlist&gt; </span></span></div>
#+END_EXPORT

** Scraping websites with Haskell · taylor.fausak.me

Captured On: [2019-04-11 16:20:13]

#+BEGIN_EXPORT html
<div dir="ltr"><a href="https://taylor.fausak.me/2015/05/21/scraping-websites-with-haskell/">https://taylor.fausak.me/2015/05/21/scraping-websites-with-haskell/</a><br><br></div>
#+END_EXPORT
